---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04
  - name: centos-7.0
    driver:
      box: parallels/centos-7.0

suites:
  - name: default
    run_list:
      - recipe[deploy-user::default]
    attributes:
